;;; SPDX-License-Identifier: GPL-3.0-or-later
;;;
;;; Haunt (https://dthompson.us/projects/haunt.html) pieces for rendering a
;;; directory of plain Markdown files -- docs, not a blog -- as a site,
;;; plus two workarounds for gaps in Haunt/guile-commonmark that a docs
;;; site runs into immediately:
;;;
;;; - `docs-pages' replaces Haunt's own `flat-pages' builder, which crashes
;;;   ((wrong-type-arg struct-vtable) inside `reader-read') on any
;;;   non-Markdown file it meets while scanning its directory: it filters
;;;   by `site-file-filter' (dotfile/temp-file exclusion) rather than by
;;;   reader-matched extension, so a plain asset sitting next to your docs
;;;   -- a generated .json, an .html file -- reaches `reader-find', gets
;;;   #f back, and is handed to `reader-read' anyway (its `(#f (error
;;;   ...))' fallback clause in flat-pages.scm is unreachable dead code:
;;;   the preceding `reader' pattern is an unconstrained variable that
;;;   matches #f too). `docs-pages' filters to \".md\" during the
;;;   directory walk itself, before any reader is involved.
;;;
;;; - `render-tables' reassembles GitHub-flavored pipe tables into real
;;;   <table> markup. guile-commonmark (the reader Haunt ships) implements
;;;   plain CommonMark only, no GFM extensions, so a table is otherwise
;;;   left as one <p> of literal "|" characters.
;;;
;;; `rewrite-md-links' additionally rewrites the ".md" cross-links your doc
;;; sources use (so they still resolve when opened as plain files, e.g. on
;;; GitHub itself) to the ".html" pages this module actually builds.

(define-module (autodoc site)
  #:use-module (commonmark)
  #:use-module (haunt artifact)
  #:use-module (haunt html)
  #:use-module (haunt site)
  #:use-module (ice-9 ftw)
  #:use-module (ice-9 match)
  #:use-module (ice-9 textual-ports)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-13)
  #:export (docs-pages
            render-tables
            rewrite-md-links
            page-title
            default-template
            strip-html-comment-lines))

;;; Title extraction

(define (flatten-strings tree)
  "Depth-first list of every string leaf under TREE, so inline markup
(code spans, emphasis) inside a heading still contributes its text."
  (match tree
    ((? string? s) (list s))
    ((? pair? nodes) (append-map flatten-strings nodes))
    (_ '())))

(define (first-heading-text tree)
  "The flattened text of the first h1 node found anywhere in the commonmark
SXML TREE, or #f if there is none."
  (match tree
    (('h1 rest ...) (string-join (flatten-strings rest) ""))
    ((? pair? nodes) (any first-heading-text nodes))
    (_ #f)))

(define (page-title file-name body)
  "BODY's first # heading, or FILE-NAME's basename if it has none."
  (or (first-heading-text body)
      (basename file-name ".md")))

;;; HTML-comment stripping

(define (strip-html-comment-lines text)
  "Drop standalone single-line HTML-comment lines (e.g. a generator's
\"<!-- Generated by ...; do not edit. -->\" marker) from TEXT.
guile-commonmark has no HTML-block support and raises \"unknown node\" on
them; this only affects what gets fed to the renderer, not the source file
on disk."
  (string-join
   (remove (lambda (line)
             (and (string-prefix? "<!--" (string-trim line))
                  (string-suffix? "-->" (string-trim-right line))))
           (string-split text #\newline))
   "\n"))

;;; Link rewriting

(define* (rewrite-href href #:key (local-suffix ".html") (external-prefix #f))
  "Rewrite a Markdown-sourced HREF: a same-tree \"foo.md\" (optionally with
a #fragment) becomes \"foo{LOCAL-SUFFIX}\"; a \"../foo.md\" escaping the
docs tree becomes EXTERNAL-PREFIX + \"foo.md\" + fragment when
EXTERNAL-PREFIX is given (e.g. a GitHub blob URL, so a link to a
repo-root file the site doesn't publish still resolves), or is left alone
otherwise. Absolute, anchor-only, and scheme-qualified (http:, mailto:)
links are never touched."
  (if (or (string-null? href)
          (string-prefix? "#" href)
          (string-prefix? "http://" href)
          (string-prefix? "https://" href)
          (string-prefix? "mailto:" href))
      href
      (let* ((hash (string-index href #\#))
             (path (if hash (substring href 0 hash) href))
             (fragment (if hash (substring href hash) "")))
        (cond
         ((and external-prefix (string-prefix? "../" path))
          (string-append external-prefix (substring path 3) fragment))
         ((string-suffix? ".md" path)
          (string-append (substring path 0 (- (string-length path) 3))
                         local-suffix fragment))
         (else href)))))

(define* (rewrite-md-links tree #:key (local-suffix ".html") (external-prefix #f))
  "Rewrite every <a href=...> in commonmark SXML TREE per `rewrite-href'."
  (match tree
    (('a ('@ attrs ...) body ...)
     `(a (@ ,@(map (match-lambda
                     ((k v) (if (eq? k 'href)
                               (list k (rewrite-href v #:local-suffix local-suffix
                                                     #:external-prefix external-prefix))
                               (list k v))))
                   attrs))
         ,@(map (lambda (child) (rewrite-md-links child #:local-suffix local-suffix
                                              #:external-prefix external-prefix))
                body)))
    ((? pair? nodes) (map (lambda (child) (rewrite-md-links child #:local-suffix local-suffix
                                                        #:external-prefix external-prefix))
                          nodes))
    (other other)))

;;; GFM pipe-table reassembly

(define (soft-break? node)
  (and (string? node) (string=? node "\n")))

(define (split-on-newline-string children)
  "Split CHILDREN, a paragraph's mixed string/element children, into a list
of per-line child-lists wherever an exact \"\\n\" string node (a soft line
break) occurs."
  (let loop ((children children) (line '()) (lines '()))
    (cond
     ((null? children) (reverse (cons (reverse line) lines)))
     ((soft-break? (car children))
      (loop (cdr children) '() (cons (reverse line) lines)))
     (else
      (loop (cdr children) (cons (car children) line) lines)))))

(define (looks-like-table-row? line)
  "LINE is a per-line child-list. True if it opens and closes with a bare
\"|\"-bearing string, i.e. it came from a source line starting and ending
with a pipe."
  (and (pair? line)
       (string? (car line))
       (string-prefix? "|" (string-trim (car line)))
       (string? (car (last-pair line)))
       (string-suffix? "|" (string-trim-right (car (last-pair line))))))

(define (split-row-on-bar line)
  "Split one row's child-list on top-level \"|\" characters inside its
string children (a \"|\" inside a cell's own text, e.g. a code span
containing one, is not handled). Non-string children -- already inline-
parsed elements like <code> or <em> -- are pushed into the current cell
whole."
  (define (flush cell cells) (cons (reverse cell) cells))
  (let loop ((line line) (cell '()) (cells '()))
    (cond
     ((null? line) (reverse (flush cell cells)))
     ((string? (car line))
      (let piece-loop ((pieces (string-split (car line) #\|)) (cell cell) (cells cells))
        (if (null? (cdr pieces))
            (loop (cdr line) (cons (car pieces) cell) cells)
            (piece-loop (cdr pieces) '() (flush (cons (car pieces) cell) cells)))))
     (else
      (loop (cdr line) (cons (car line) cell) cells)))))

(define (trim-cell cell)
  "Trim leading whitespace off CELL's first child and trailing whitespace
off its last, when those children are strings; interior structure (code
spans, emphasis) is left untouched."
  (match cell
    (() '())
    ((only)
     (if (string? only) (list (string-trim-both only)) (list only)))
    ((first middle ... last)
     (append (list (if (string? first) (string-trim first) first))
             middle
             (list (if (string? last) (string-trim-right last) last))))))

(define (row-cells line)
  "Cells of one table row, with the empty leading/trailing artifacts the
row's own enclosing \"|\" characters produce in `split-row-on-bar' dropped."
  (let ((cells (split-row-on-bar line)))
    (map trim-cell (drop-right (drop cells 1) 1))))

(define (separator-row? cells)
  (every (lambda (cell)
           (match cell
             (((? string? s))
              (string-every (lambda (c) (or (char=? c #\-) (char=? c #\:)
                                            (char-whitespace? c)))
                            s))
             (_ #f)))
         cells))

(define (table-paragraph->table children)
  "Given a <p>'s CHILDREN, return a <table> sxml node if they form a pipe
table, or #f otherwise."
  (define lines (split-on-newline-string children))
  (and (>= (length lines) 2)
       (every looks-like-table-row? lines)
       (let* ((rows (map row-cells lines))
              (header (car rows))
              (rest (cdr rows)))
         (and (pair? rest) (separator-row? (car rest))
              `(table
                (thead (tr ,@(map (lambda (cell) `(th ,@cell)) header)))
                (tbody ,@(map (lambda (row) `(tr ,@(map (lambda (cell) `(td ,@cell)) row)))
                              (cdr rest))))))))

(define (render-tables tree)
  (match tree
    (('p children ...)
     (or (table-paragraph->table children)
         `(p ,@(map render-tables children))))
    ((? pair? nodes) (map render-tables nodes))
    (other other)))

;;; Page builder

(define* (docs-pages directory #:key template (prefix "/") (strip-comments? #t))
  "A Haunt builder rendering every \".md\" file under DIRECTORY to an
\".html\" page at the mirrored path under PREFIX, title from its first
heading (`page-title'), tables reassembled (`render-tables'), and internal
links rewritten (`rewrite-md-links', called with no EXTERNAL-PREFIX --
compose your own directory walk if you need one).

TEMPLATE is called as (TEMPLATE site title body) and must return a
complete SXML document; see `default-template' for a ready one.

Unlike Haunt's own `flat-pages', this only ever looks at \".md\" files (see
this module's commentary), so it can safely share a directory with
generated non-Markdown assets."
  (lambda (site posts)
    (define (enter? file-name stat memo) #t)
    (define (noop file-name stat memo) memo)
    (define (leaf file-name stat memo)
      (if (string-suffix? ".md" file-name) (cons file-name memo) memo))
    (define (err file-name stat errno memo)
      (error "docs-pages: directory scan failed" file-name errno))
    (define src-files
      (file-system-fold enter? leaf noop noop noop err '() directory))
    (map (lambda (file-name)
           (call-with-input-file file-name
             (lambda (in-port)
               (define text (get-string-all in-port))
               (define port
                 (open-input-string (if strip-comments?
                                        (strip-html-comment-lines text)
                                        text)))
               (let* ((body (render-tables (rewrite-md-links (commonmark->sxml port))))
                      (title (page-title file-name body))
                      (dir (substring (dirname file-name) (string-length directory)))
                      (out (string-append prefix dir
                                          (if (string-null? dir) "" "/")
                                          (basename file-name ".md") ".html")))
                 (serialized-artifact out (template site title body) sxml->html)))))
         src-files)))

;;; A minimal default template

(define* (default-template site title body #:key (index-href "/index.html"))
  "A small, theme-neutral SXML page template: monospace, light/dark aware,
readable table/code defaults. Good enough to start from; pass your own
TEMPLATE to `docs-pages' for anything more opinionated."
  `((doctype "html")
    (html (@ (lang "en"))
     (head
      (meta (@ (charset "utf-8")))
      (meta (@ (name "viewport") (content "width=device-width,initial-scale=1")))
      (title ,(if (string=? title (site-title site))
                  title
                  (string-append title " — " (site-title site))))
      (style "
:root{--bg:#fff;--ink:#0a0a0a;--muted:#565656;--soft:#d4d4d4}
@media(prefers-color-scheme:dark){:root{--bg:#0a0a0a;--ink:#ededed;--muted:#a0a0a0;--soft:#333}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);
     font:15px/1.6 ui-monospace,'IBM Plex Mono',monospace}
.page{width:min(760px,calc(100% - 32px));margin:0 auto;padding:24px 0 60px}
nav{font-size:12px;letter-spacing:.06em;text-transform:uppercase;
    border-bottom:2px solid var(--ink);padding-bottom:10px;margin-bottom:20px}
nav a{color:inherit}
h1,h2,h3{line-height:1.2}
h1{border-bottom:1px solid var(--soft);padding-bottom:8px}
a{color:inherit;text-underline-offset:2px}
pre{background:color-mix(in srgb,var(--ink) 6%,var(--bg));
    padding:10px 12px;overflow-x:auto}
code{font-family:inherit}
table{border-collapse:collapse;width:100%}
th,td{border-bottom:1px solid var(--soft);padding:5px 8px;text-align:left}
footer{margin-top:40px;padding-top:10px;border-top:1px solid var(--soft);
       font-size:12px;color:var(--muted)}"))
     (body
      (div (@ (class "page"))
       (nav (a (@ (href ,index-href)) ,(site-title site)))
       ,body)))))
